/*
  POSTS.JS
  ========
  This file is your "backend." Every post on the site is one JavaScript
  object in the POSTS array below. To publish a new post:

    1. Open write.html in your browser (double-click it, no server needed).
    2. Fill in the details.
    3. Click "Generate post code" and copy the snippet it gives you.
    4. Paste that snippet as a NEW entry at the TOP of the POSTS array below.
    5. Save this file and re-upload it to your host (or push to git).

  Newest post should always be first in the array — the site does not
  re-sort them for you.

  Fields:
    slug        — used in the URL, auto-generated by write.html
    title       — headline
    subtitle    — one line shown under the title on cards and the post page
    date        — YYYY-MM-DD
    category    — ONE primary category, must match one of the tabs in
                  js/categories.js (e.g. "AI Security", "Cloud Security")
    tags        — array of extra tag pills shown on the post
    featured    — true for posts you want in the large top cards on the
                  homepage (keep this to 0–2 posts at a time)
    excerpt     — 1–2 sentence summary shown on cards
    contentHTML — the full post body
*/

const POSTS = [
  {
    slug: "why-ai-agents-need-their-own-perimeter",
    title: "Why AI Agents Need Their Own Security Perimeter",
    subtitle: "Treating an agent like a user account misses most of the actual risk.",
    date: "2026-09-20",
    category: "AI Security",
    tags: ["AI Security", "MCP", "Governance"],
    featured: true,
    excerpt:
      "Most enterprises are securing AI agents the same way they secure employees. That model breaks down fast once an agent can call tools, chain actions, and touch data no single login would ever reach.",
    contentHTML: `
      <p>An employee account has a fairly predictable blast radius: whatever that person's role allows. An AI agent doesn't work like that. Give it a browsing tool, a code execution sandbox, and access to a shared drive, and its effective reach becomes the union of every tool it's connected to — which is rarely reviewed as a single surface.</p>
      <h2>Where the model breaks</h2>
      <p>Most identity and access frameworks were built around a human doing one thing at a time, approving each step. Agents chain steps autonomously, which means a single prompt injection or a misconfigured MCP server can turn a narrow task into a much larger one before anyone notices.</p>
      <ul>
        <li>Tool permissions are usually granted once and rarely re-evaluated per-task</li>
        <li>Data an agent reads for context often isn't logged the way a direct query would be</li>
        <li>Multi-agent setups multiply this: one agent's output becomes another agent's untrusted input</li>
      </ul>
      <h2>What a real perimeter looks like</h2>
      <p>In practice, this means treating agent traffic as its own category rather than folding it into existing user-based policies: inspecting prompts and responses, discovering which MCP servers and embedded AI tools are even in use, and applying data protection at the point where the agent reads or writes data — not just at login.</p>
      <p>This is the part of AI security that's still genuinely unsolved at most organizations. The tooling is catching up, but the mental model — "an agent is a very fast user" — needs to change first.</p>
    `,
  },
  {
    slug: "mcp-servers-the-new-shadow-it",
    title: "MCP Servers Are the New Shadow IT",
    subtitle: "Every team is standing one up. Almost none of them are inventoried.",
    date: "2026-09-17",
    category: "AI Security",
    tags: ["MCP", "Shadow IT", "Discovery"],
    featured: true,
    excerpt:
      "Model Context Protocol servers are spreading through engineering orgs the way unsanctioned SaaS apps did a decade ago — fast, useful, and completely invisible to security teams until something goes wrong.",
    contentHTML: `
      <p>A few years ago it was an engineer connecting a personal Dropbox to a work laptop. Today it's a developer spinning up an MCP server that hands an AI agent read access to a production database, a ticketing system, or internal docs — often in an afternoon, often without telling anyone.</p>
      <p>The pattern is familiar to anyone who lived through the first wave of SaaS sprawl: individually reasonable decisions add up to an inventory nobody owns.</p>
      <h2>Why this one is harder to catch</h2>
      <p>Unsanctioned SaaS at least showed up in network traffic to a recognizable domain. MCP traffic often looks like ordinary application traffic on infrastructure the company already trusts, which means classic CASB-style discovery has to evolve to fingerprint MCP behavior specifically — not just flag an unfamiliar destination.</p>
      <h2>What's worked so far</h2>
      <ul>
        <li>Discovery focused on MCP-specific traffic patterns, not just domain reputation</li>
        <li>Treating each MCP server as its own asset with an owner, not folding it into "AI tools" generically</li>
        <li>Requiring the same data-handling review for an MCP server that a new SaaS vendor would get</li>
      </ul>
      <p>None of this is exotic. It's the same governance muscle most security teams already have — it just needs to be pointed at a category that didn't exist eighteen months ago.</p>
    `,
  },
  {
    slug: "prompt-injection-is-not-a-someday-problem",
    title: "Prompt Injection Isn't a 'Someday' Problem",
    subtitle: "It's already showing up in production traffic. Most teams just aren't looking.",
    date: "2026-09-12",
    category: "AI Security",
    tags: ["Prompt Injection", "AI Security", "Detection"],
    featured: false,
    excerpt:
      "Prompt injection gets talked about like a research curiosity. In the traffic I've actually reviewed, it's already a live, if usually low-stakes, category of attempted abuse.",
    contentHTML: `
      <p>A lot of prompt injection discussion happens at the conference-talk level of abstraction: theoretical jailbreaks, clever paper examples. What's less discussed is what it looks like in ordinary enterprise traffic once you actually go looking for it.</p>
      <h2>What inspection actually catches</h2>
      <p>The bulk of what shows up isn't sophisticated. It's users testing boundaries, third-party documents with embedded instructions aimed at whatever model eventually reads them, and the occasional deliberate attempt to extract a system prompt. Individually low severity — but they establish that the attack surface is live, not hypothetical, and that it needs the same monitoring discipline as any other input channel.</p>
      <ul>
        <li>Inspect both prompts and responses, not just prompts — injected instructions often only reveal themselves in what the model does next</li>
        <li>Log AI interactions with enough context to investigate after the fact, not just a pass/fail classification</li>
        <li>Treat documents and web content fed to an AI agent as untrusted input, the same way you'd treat file uploads</li>
      </ul>
      <p>None of this requires exotic tooling. It requires deciding that AI traffic deserves the same inspection rigor as any other data flow crossing a trust boundary — and then actually building the pipeline to do it.</p>
    `,
  },
  {
    slug: "casb-lessons-that-still-apply-to-ai-governance",
    title: "5 CASB Lessons That Apply Directly to AI Governance",
    subtitle: "We already solved a version of this problem once.",
    date: "2026-09-05",
    category: "Cloud Security",
    tags: ["CASB", "AI Governance", "SSPM"],
    featured: false,
    excerpt:
      "Before AI agents, it was unsanctioned SaaS. The discovery-then-govern playbook from the CASB era maps onto AI adoption more directly than most teams realize.",
    contentHTML: `
      <p>When CASB tools first showed up, the pitch was simple: you can't secure what you can't see, and most organizations had far more SaaS in use than IT had approved. AI adoption today looks almost identical, just faster.</p>
      <h2>The five lessons</h2>
      <ol>
        <li><strong>Discovery has to come before policy.</strong> You cannot write a sane AI usage policy for tools you don't know exist.</li>
        <li><strong>Shadow usage is a signal, not just a risk.</strong> Wherever employees route around official tools, that's telling you something about a gap in what's officially offered.</li>
        <li><strong>Inline visibility beats log review.</strong> Reviewing what happened yesterday is a weaker control than seeing and acting on it as it happens.</li>
        <li><strong>Data protection has to travel with the data</strong>, not sit at the perimeter — this was true for SaaS and is even more true when an AI agent can summarize, transform, and re-route sensitive data in ways a simple DLP rule won't recognize.</li>
        <li><strong>Governance that blocks everything gets bypassed.</strong> The CASB programs that worked gave people a fast, sanctioned path — not just a wall.</li>
      </ol>
      <p>None of this is a new discipline. It's the same one, pointed at a faster-moving target.</p>
    `,
  },
];
